/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualBuildRouteImport } from './routes/manual-build'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutoKeypointsRouteImport } from './routes/auto-keypoints'
import { Route as ApprovalLogRouteImport } from './routes/approval-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewReviewIdRouteImport } from './routes/review.$reviewId'

const ManualBuildRoute = ManualBuildRouteImport.update({
  id: '/manual-build',
  path: '/manual-build',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoKeypointsRoute = AutoKeypointsRouteImport.update({
  id: '/auto-keypoints',
  path: '/auto-keypoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalLogRoute = ApprovalLogRouteImport.update({
  id: '/approval-log',
  path: '/approval-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewReviewIdRoute = ReviewReviewIdRouteImport.update({
  id: '/review/$reviewId',
  path: '/review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approval-log': typeof ApprovalLogRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approval-log': typeof ApprovalLogRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approval-log': typeof ApprovalLogRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approval-log'
    | '/auto-keypoints'
    | '/dashboard'
    | '/login'
    | '/manual-build'
    | '/review/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approval-log'
    | '/auto-keypoints'
    | '/dashboard'
    | '/login'
    | '/manual-build'
    | '/review/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/approval-log'
    | '/auto-keypoints'
    | '/dashboard'
    | '/login'
    | '/manual-build'
    | '/review/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalLogRoute: typeof ApprovalLogRoute
  AutoKeypointsRoute: typeof AutoKeypointsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ManualBuildRoute: typeof ManualBuildRoute
  ReviewReviewIdRoute: typeof ReviewReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual-build': {
      id: '/manual-build'
      path: '/manual-build'
      fullPath: '/manual-build'
      preLoaderRoute: typeof ManualBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-keypoints': {
      id: '/auto-keypoints'
      path: '/auto-keypoints'
      fullPath: '/auto-keypoints'
      preLoaderRoute: typeof AutoKeypointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-log': {
      id: '/approval-log'
      path: '/approval-log'
      fullPath: '/approval-log'
      preLoaderRoute: typeof ApprovalLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$reviewId': {
      id: '/review/$reviewId'
      path: '/review/$reviewId'
      fullPath: '/review/$reviewId'
      preLoaderRoute: typeof ReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalLogRoute: ApprovalLogRoute,
  AutoKeypointsRoute: AutoKeypointsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ManualBuildRoute: ManualBuildRoute,
  ReviewReviewIdRoute: ReviewReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
