/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualBuildRouteImport } from './routes/manual-build'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutoKeypointsRouteImport } from './routes/auto-keypoints'
import { Route as IndexRouteImport } from './routes/index'

const ManualBuildRoute = ManualBuildRouteImport.update({
  id: '/manual-build',
  path: '/manual-build',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoKeypointsRoute = AutoKeypointsRouteImport.update({
  id: '/auto-keypoints',
  path: '/auto-keypoints',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-keypoints': typeof AutoKeypointsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manual-build': typeof ManualBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auto-keypoints' | '/dashboard' | '/login' | '/manual-build'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auto-keypoints' | '/dashboard' | '/login' | '/manual-build'
  id:
    | '__root__'
    | '/'
    | '/auto-keypoints'
    | '/dashboard'
    | '/login'
    | '/manual-build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoKeypointsRoute: typeof AutoKeypointsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ManualBuildRoute: typeof ManualBuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual-build': {
      id: '/manual-build'
      path: '/manual-build'
      fullPath: '/manual-build'
      preLoaderRoute: typeof ManualBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-keypoints': {
      id: '/auto-keypoints'
      path: '/auto-keypoints'
      fullPath: '/auto-keypoints'
      preLoaderRoute: typeof AutoKeypointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoKeypointsRoute: AutoKeypointsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ManualBuildRoute: ManualBuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
